### PR TITLE
Evens

### PR DESCRIPTION
**Pull request by SandraJones**
All current Integer items have passing tests, other than the one Jurnell did in class. 
This PR is covering the Integer.cs and IntegerTests.cs.

### CODE REVIEW

**Comment by katerebekah** [comment]
What are you doing with your integer class? All the functionality is now tested, so I will thumbs up it, but I'm not sure how what you are doing will fulfill the requirements of the assignment. 👍

**Comment by katerebekah** [comment]
You may want to discuss your approach to the assignment with Jurnell or Blaise tomorrow

**Comment by BlaiseGratton** [comment]
Keep in mind the end goal is to produce a list of integers - once you get the Integer constructor configured, try getting a method to produce a list of integers according to a length parameter.

**Comment by SandraJones** [comment]
We put methods into the Integer class for later use. Our Integer class is a parent class to all other classes, such as evens, odds, etc.  Regarding creating the list, we will get to that. We wanted to make sure we had good data to work with (at least that is what we were aiming for), and tried to go back and forth between the test and the regular Integer file.

**Comment by SandraJones** [comment]
Thank you very much! I see that I did misunderstand the intent of the assignment. Will adjust code and do a new PR.

**Pull request closed without merging**
